name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Checkout AI Code Reviewer Agent
        uses: actions/checkout@v4
        with:
          repository: AjAyrAo43/Ai-code-reviewer
          path: ai-code-reviewer

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ./ai-code-reviewer
        run: |
          pip install -r requirements.txt

      - name: Run AI Code Review
        working-directory: ./ai-code-reviewer
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          python src/main.py
